import requests
import random

API_URL = "http://localhost:8000/jobs"

# Payload generators for each job type
def generate_email_payload():
    return {
        "to": f"user{random.randint(1, 100)}@example.com",
        "subject": f"Test Email #{random.randint(1000, 9999)}",
        "body": "This is a test email body generated by the seed script."
    }

def generate_report_payload():
    return {
        "report_type": random.choice(["sales", "inventory", "analytics", "performance"]),
        "format": random.choice(["pdf", "csv"]),
        "date_range": {
            "start": "2026-01-01",
            "end": "2026-01-31"
        }
    }

def generate_notification_payload():
    return {
        "user_id": f"U-{random.randint(10000, 99999)}",
        "channel": random.choice(["push", "sms", "email"]),
        "message": f"Alert: System notification #{random.randint(1, 1000)}"
    }

PAYLOAD_GENERATORS = {
    "email": generate_email_payload,
    "report": generate_report_payload,
    "notification": generate_notification_payload
}

def seed_data():
    print(f"Seeding data to {API_URL}...")
    
    # Create 20 jobs to test the queue
    for i in range(20): 
        job_type = random.choice(["email", "report", "notification"])
        payload = {
            "type": job_type,
            "priority": random.randint(1, 5),
            "payload": PAYLOAD_GENERATORS[job_type]()
        }
        
        try:
            response = requests.post(API_URL, json=payload)
            response.raise_for_status()
            data = response.json()
            print(f"Created Job {data['id'][:8]}... [Type: {job_type}, Priority: {data['priority']}]")
        except Exception as e:
            print(f"Failed to create job: {e}")

    print("\nSeeding complete. Check http://localhost:3000/stats to see queue status.")

if __name__ == "__main__":
    seed_data()